### ISSUE TITLE
Does it work on Firefox Quantum?

### ISSUE THREAD

**Issue by eralpkaraduman** [SamHH/share-for-helium#15]
Can't see any UI to share it on Firefox Quantum 59.0.2

**Comment by samhh** [comment]
I'm seeing it on a clean Firefox 60 install.

Make sure you're not trying to access it in the context menu on the Firefox addon store; it might be that there are some security restrictions that prevent addons from operating there.

**Comment by eralpkaraduman** [comment]
Got it,
Sorry i was expecting to see it in the toolbar, figured it is actually in the right click menu.
Closing, thanks.
